[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aman-t-t-backend"
version = "0.1.0"
description = "Backend Application"
requires-python = ">=3.8"
dependencies = [
    # Apni zaroori dependencies yahan daalein (FastAPI, uvicorn etc.)
    # pywinpty yahan mat likhna
]

[tool.setuptools.packages.find]
where = ["."]
include = ["routes*", "models*", "config*", "schemas*", "database*", "dependencies*"]
